# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fadde77f29d14b272f3f046a36c89e5570f501bcf24d8a2697cd8980f1c2aab75ca24f8fbd23b1aa26eb36bcb791acd5120a01af72ccfe741e5228615d85d4b9

test:
  secret_key_base: 6d51ade56918d1c00fc649dcc3227e0d4f257452c6cd64b147858083cae961bdb712cf2e73abb48f1771a627d0e043fbf8ead59053ef98c5fba6228982f124d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
